"""The migrations build exactly the schema ``tables.py`` declares, and undo it.

Plain ``def`` tests: ``migrations/env.py`` runs ``asyncio.run``, which cannot
start inside the event loop an async test runs on.
"""

from __future__ import annotations

from contextlib import contextmanager
from typing import TYPE_CHECKING

import pytest
from alembic import command
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import Column, Integer, Table, create_engine, inspect, make_url

from my_app.adapters.sql.tables import metadata

if TYPE_CHECKING:
    from collections.abc import Iterator

    from sqlalchemy import Inspector


@contextmanager
def _inspect(url: str) -> Iterator[Inspector]:
    # A blocking engine on the same file: these tests run outside any loop.
    engine = create_engine(make_url(url).set(drivername="sqlite"))
    try:
        with engine.connect() as connection:
            yield inspect(connection)
    finally:
        engine.dispose()


def test_upgrade_head_matches_metadata(alembic_config, sqlite_url):
    command.upgrade(alembic_config, "head")

    # Raises AutogenerateDiffsDetected if a revision would hold any operation.
    command.check(alembic_config)
    with _inspect(sqlite_url) as inspector:
        assert set(inspector.get_table_names()) == {"alembic_version", "todos"}


def test_upgrade_head_creates_todos_as_tables_declares(alembic_config, sqlite_url):
    command.upgrade(alembic_config, "head")

    with _inspect(sqlite_url) as inspector:
        columns = {
            column["name"]: column["nullable"]
            for column in inspector.get_columns("todos")
        }
        primary_key = inspector.get_pk_constraint("todos")

    assert columns == {
        "id": False,
        "title": False,
        "is_completed": False,
        "created_at": False,
    }
    assert primary_key == {"constrained_columns": ["id"], "name": "pk_todos"}


def test_check_table_missing_from_migrations_raises_naming_it(alembic_config):
    command.upgrade(alembic_config, "head")
    unmigrated = Table("unmigrated", metadata, Column("id", Integer, primary_key=True))
    try:
        with pytest.raises(AutogenerateDiffsDetected, match=r"unmigrated"):
            command.check(alembic_config)
    finally:
        metadata.remove(unmigrated)


def test_downgrade_base_leaves_no_todos_table(alembic_config, sqlite_url):
    command.upgrade(alembic_config, "head")

    command.downgrade(alembic_config, "base")

    with _inspect(sqlite_url) as inspector:
        assert "todos" not in inspector.get_table_names()


def test_upgrade_without_database_url_raises_naming_the_variable(
    alembic_config, monkeypatch
):
    monkeypatch.delenv("MY_APP_DATABASE_URL")

    with pytest.raises(RuntimeError, match=r"^MY_APP_DATABASE_URL must be set"):
        command.upgrade(alembic_config, "head")
